#--------------------------------factors with data
getwd()
setwd("C:\\Users\\ziyan\\OneDrive\\Desktop\\R programming A-Z Udemy\\Advance Visualization with GGPlot2")
getwd()

movies <- read.csv("Movie Ratings.csv")
head(movies)
colnames(movies) <- c("Film" , "Genre" , "CriticRating" ,"AudienceRating" , "BudgetMillions" , "Year")
head(movies)
tail(movies)
str(movies)

summary(movies)
#year is non factor , need to convert it to factor

factor(movies$Year)
#converting column into a factor 
movies$Year <- factor(movies$Year)

summary(movies)

#--------------------------Aesthetics layer
#use aes() function to map the data 
ggplot(data = movies, aes(x = CriticRating, y = AudienceRating))

#add geometry
ggplot(data = movies, aes(x = CriticRating, y = AudienceRating)) + 
  geom_point()

#add colour 
ggplot(data = movies, aes(x = CriticRating, y = AudienceRating , colour= Genre)) + 
  geom_point()


#add size
ggplot(data = movies, aes(x = CriticRating, y = AudienceRating , colour= Genre,
                          size=Genre)) + 
  geom_point()

#add size - better way
ggplot(data = movies, aes(x = CriticRating, y = AudienceRating , colour= Genre,
                          size= BudgetMillions)) + 
  geom_point()

#--------------- Plotting with Layers
#everytime when we have to add a layer , we need to add an object 

p <-ggplot(data = movies, aes(x = CriticRating, y = AudienceRating , colour= Genre,
                              size= BudgetMillions))

#point
p + geom_point()

#lines
p + geom_line()

#multiple layers
p + geom_point() + geom_line()
#this means points are plotted on top of the line layers
p + geom_line() + geom_point()

#-------------------- Overriding Aesthetics
#initial
q <- ggplot(data = movies, aes(x = CriticRating, y = AudienceRating , colour= Genre,
                               size= BudgetMillions))

#add geom layer
q + geom_point()

#overriding aes
#eg1
q + geom_point(aes(size = CriticRating)) #the geom point size override the initial one

#eg2
q + geom_point(aes(colour=BudgetMillions))

#q remains the same 
q + geom_point()

#ex3
q + geom_point(aes(x = BudgetMillions)) + xlab("BudgetMillions $$$")

#ex4
q + geom_line() + geom_point()
#reduce line size 
q + geom_line(size = 1) + geom_point()

#---------------------Mapping vs Setting Aesthetics (IMPORTANT CONCEPT)
 
r <- ggplot(data= movies, aes(x=CriticRating, y=AudienceRating))
r + geom_point()

#Add colour
#1 Mapping (what we've done so far);
r + geom_point(aes(colour= Genre))
#2 setting:
r + geom_point(colour= "DarkGreen")
#ERROR
#r _ geom_point(aes(colour = "DarkGreen"))

#1 Mapping
r + geom_point(aes(size = BudgetMillions))
#2 Setting 
r + geom_point(size= 10)

#------------------------- Histograms vs Density Charts
s <- ggplot(data = movies, aes(x=BudgetMillions))
#count(y-axis)is generated by R 
s+ geom_histogram(binwidth = 10)

#add colour
s + geom_histogram(binwidth = 10, aes(fill=Genre))
#add a border
s + geom_histogram(binwidth = 10, aes(fill=Genre), colour= "Black")

#sometimes you may need density charts
#this is for probability charts
s + geom_density(aes(fill=Genre))
s + geom_density(aes(fill=Genre), position = "stack")

#--------------------------starting layers tip 

t <- ggplot(data=movies, aes(x=AudienceRating))
t + geom_histogram(binwidth =  10, fill="White" , colour= "Blue")

#another way (using the overriding )
t <- ggplot(data= movies) #this has more flexibility 
t + geom_histogram(binwidth = 10, aes(x=AudienceRating), 
                   fill = "White", colour = "Blue")
                                        
#>>>> 4
t + geom_histogram(binwidth= 10, aes(x=CriticRating), 
                   fill = "White", colour= "Blue")

#>>>> 5
#this is a skeleton plot 
t <- ggplot()

#--------------------------Statistical Transformations
?geom_soomth #help to see the data more clearly with lines

u <- ggplot(data=movies, aes(x=CriticRating, y=AudienceRating,
                             colour= Genre))
u + geom_point() + geom_smooth(fill=NA)

#boxplots
u <- ggplot(data=movies, aes(x=Genre, y=AudienceRating,colour= Genre))

u + geom_boxplot()
u + geom_boxplot(size= 1.2)
u + geom_boxplot(size= 1.2) + geom_point()

#tip/hack:
u + geom_boxplot(size=1.2) + geom_jitter()
#another way:
u + geom_jitter() + geom_boxplot(size=1.2, alpha=0.5)
#>>>> 6

#----------------Using Facets


v <- ggplot(data<- movies, aes(x=BudgetMillions))
v + geom_histogram(binwidth = 10, aes(fill=Genre),
                   colour = "Black")

#histogram for each of the genre
#facets

v + geom_histogram(binwidth = 10, aes(fill = Genre),
                   colour = "Black") +
  facet_grid(Genre~. , scales="free") #scales

#scatterplots:
w<- ggplot(data <- movies, aes(x=CriticRating, y = AudienceRating,
                               colour=Genre))
w + geom_point(size=3)

#facets
w + geom_point(size = 3) + facet_grid(Genre~.)
w + geom_point(size = 3) + facet_grid(.~Year)
w + geom_point(size = 3) + geom_smooth() +facet_grid(Genre~Year)
w + geom_point(aes(size=BudgetMillions)) + geom_smooth() + 
  facet_grid(Genre~Year)


#-------------------- Coordinates

#Today:
#limits
#zoom

m <- ggplot(data = movies, aes(x=CriticRating, y = AudienceRating, 
                               size= BudgetMillions,
                               colour = Genre))
m + geom_point()

m + geom_point() + xlim(50,100) + ylim(50,100)

#wont work well always 
n <- ggplot(data= movies, aes(x= BudgetMillions))
n + geom_histogram(binwidth = 10, aes(fill=Genre), colour="Black")+
  ylim(0,50)

#instead - zoom:
n + geom_histogram(binwidth = 10, aes(fill=Genre) , colour= "Black")+
  coord_cartesian(ylim=c(0,50)) #this is the layering

#improve 1:

w + geom_point(aes(size=BudgetMillions)) + geom_smooth() + 
  facet_grid(Genre~Year) + coord_cartesian(ylim=c(0,100))


#--------------------------- Theme
o <- ggplot(data= movies, aes(x= BudgetMillions))

h <- o + geom_histogram(binwidth = 10, aes(fill = Genre),
                   colour = "Black")

#axes label 
h + xlab("Money axis") +
  ylab("Number of Movies") +
  theme(axis.title.x = element_text(colour="DarkGreen", size= 30),
        axis.title.y = element_text(colour="Red", size = 30),
        axis.text = element_text(size=20),
        axis.text.y = element_text(size = 20))

#legend formatting

h + xlab("Money axis") +
  ylab("Number of Movies") +
  theme(axis.title.x = element_text(colour="DarkGreen", size= 30),
        axis.title.y = element_text(colour="Red", size = 30),
        axis.text = element_text(size=20),
        axis.text.y = element_text(size = 20),
        
        legend.title = element_text(size=30) , 
        legend.text = element_text(size=20) , 
        legend.position = c(1,1) , 
        legend.justification = c(1,1))

#title
h + xlab("Money axis") +
  ylab("Number of Movies") +
  ggtitle("Movie Budget Distribution") +
  theme(axis.title.x = element_text(colour="DarkGreen", size= 30),
        axis.title.y = element_text(colour="Red", size = 30),
        axis.text.x = element_text(size=20),
        axis.text.y = element_text(size = 20),
        
        legend.title = element_text(size=30) , 
        legend.text = element_text(size=20) , 
        legend.position = c(1,1) , 
        legend.justification = c(1,1) , 
        
        plot.title = element_text(colour="DarkBlue", 
                                  size =40,
                                  family="Courier"))
        






